### ISSUE TITLE
[BUG] <title>指定GPU部分情况失效，会调用非指定GPU导致CUDA out of memory

### ISSUE THREAD

**Issue by xyhellowater** [netease-youdao/QAnything#202]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

使用命令bash ./run.sh -c local -i 2,3 -b hf -m Qwen-7B-QAnything -t qwen-7b-qanything启动服务时，会出现爆内存提示，但是提示的是GPU0内存爆了，但我并未指定要使用GPU0。
![01](https://github.com/netease-youdao/QAnything/assets/51786144/ab715434-0854-45c5-800e-1566b248f6b4)
![02](https://github.com/netease-youdao/QAnything/assets/51786144/2033c63a-a16e-4b4e-8555-1a4f85ce4439)

### 期望行为 | Expected Behavior

理论上来说，我指定的二张V100具有足量的GPU来支持7B模型的启动。但是不知为何出现了GPU0的爆内存错误。
期望将Quadro V100加入到可支持的选项卡中，我现在时手动将其加入了可支持列表.

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 18.04
- NVIDIA Driver:535.129.03
- CUDA:官方docker
- docker: 20.10.21
- docker-compose: 2.24.7
- NVIDIA GPU: Quadro GV100
- NVIDIA GPU Memory:32768MiB
```

### QAnything日志 | QAnything logs

2024-03-29 10:34:00 | INFO | model_worker | args: Namespace(host='0.0.0.0', port=7801, worker_address='http://0.0.0.0:7801', controller_address='http://0.0.0.0:7800', model_path='/model_repos/CustomLLM/Qwen-7B-QAnything', revision='main', device='cuda', gpus='2', num_gpus=1, max_gpu_memory=None, dtype='bfloat16', load_8bit=True, cpu_offloading=False, gptq_ckpt=None, gptq_wbits=16, gptq_groupsize=-1, gptq_act_order=False, awq_ckpt=None, awq_wbits=16, awq_groupsize=-1, enable_exllama=False, exllama_max_seq_len=4096, exllama_gpu_split=None, exllama_cache_8bit=False, enable_xft=False, xft_max_seq_len=4096, xft_dtype=None, model_names=None, conv_template='qwen-7b-qanything', embed_in_truncate=False, limit_worker_concurrency=5, stream_interval=2, no_register=False, seed=None, debug=False, ssl=False)
2024-03-29 10:34:00 | INFO | model_worker | Loading the model ['Qwen-7B-QAnything'] on worker 1470aaad ...
2024-03-29 10:34:01 | INFO | stdout | Warning: import flash_attn rotary fail, please install FlashAttention rotary to get better performance https://github.com/Dao-AILab/flash-attention/tree/main/csrc/rotary
2024-03-29 10:34:01 | INFO | stdout | Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get better performance https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
2024-03-29 10:34:01 | INFO | stdout | Warning: import flash_attn fail, please install FlashAttention https://github.com/Dao-AILab/flash-attention
2024-03-29 10:34:03 | ERROR | stderr | 
  0%|          | 0/2 [00:00<?, ?it/s]
2024-03-29 10:37:06 | ERROR | stderr | 
 50%|█████     | 1/2 [03:03<03:03, 183.06s/it]
2024-03-29 10:38:49 | ERROR | stderr | 
100%|██████████| 2/2 [04:46<00:00, 136.08s/it]
2024-03-29 10:38:49 | ERROR | stderr | 
100%|██████████| 2/2 [04:46<00:00, 143.12s/it]
2024-03-29 10:38:49 | ERROR | stderr | 
2024-03-29 10:38:49 | ERROR | stderr | Traceback (most recent call last):
2024-03-29 10:38:49 | ERROR | stderr |   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2024-03-29 10:38:49 | ERROR | stderr |     return _run_code(code, main_globals, None,
2024-03-29 10:38:49 | ERROR | stderr |   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
2024-03-29 10:38:49 | ERROR | stderr |     exec(code, run_globals)
2024-03-29 10:38:49 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/serve/model_worker.py", line 375, in <module>
2024-03-29 10:38:49 | ERROR | stderr |     args, worker = create_model_worker()
2024-03-29 10:38:49 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/serve/model_worker.py", line 346, in create_model_worker
2024-03-29 10:38:49 | ERROR | stderr |     worker = ModelWorker(
2024-03-29 10:38:49 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/serve/model_worker.py", line 77, in __init__
2024-03-29 10:38:49 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2024-03-29 10:38:49 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/model/model_adapter.py", line 277, in load_model
2024-03-29 10:38:49 | ERROR | stderr |     model, tokenizer = adapter.load_compress_model(
2024-03-29 10:38:49 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/model/model_adapter.py", line 111, in load_compress_model
2024-03-29 10:38:49 | ERROR | stderr |     return load_compress_model(
2024-03-29 10:38:49 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/fastchat/model/compression.py", line 219, in load_compress_model
2024-03-29 10:38:49 | ERROR | stderr |     model.half()
2024-03-29 10:38:49 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 2470, in half
2024-03-29 10:38:49 | ERROR | stderr |     return super().half(*args)
2024-03-29 10:38:49 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1014, in half
2024-03-29 10:38:49 | ERROR | stderr |     return self._apply(lambda t: t.half() if t.is_floating_point() else t)
2024-03-29 10:38:49 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 810, in _apply
2024-03-29 10:38:49 | ERROR | stderr |     module._apply(fn)
2024-03-29 10:38:49 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 810, in _apply
2024-03-29 10:38:49 | ERROR | stderr |     module._apply(fn)
2024-03-29 10:38:49 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 833, in _apply
2024-03-29 10:38:49 | ERROR | stderr |     param_applied = fn(param)
2024-03-29 10:38:49 | ERROR | stderr |   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1014, in <lambda>
2024-03-29 10:38:49 | ERROR | stderr |     return self._apply(lambda t: t.half() if t.is_floating_point() else t)
2024-03-29 10:38:49 | ERROR | stderr | torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.16 GiB. GPU 0 has a total capacty of 10.75 GiB of which 327.50 MiB is free. Process 7510 has 10.43 GiB memory in use. Of the allocated memory 10.24 GiB is allocated by PyTorch, and 17.34 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

### 复现方法 | Steps To Reproduce

1.docker load -i qanything_offline.tar
2.cd QAnything-master
3. bash ./run.sh -c local -i 2,3 -b hf -m Qwen-7B-QAnything -t qwen-7b-qanything

### 备注 | Anything else?

我可以成功启动3B模型，但是无法启动7B模型。

**Comment by gongxiansen** [comment]
怎么解决的啊 大佬

**Comment by xyhellowater** [comment]
> 怎么解决的啊 大佬

换了个更好的卡,就不会爆了.

**Comment by gongxiansen** [comment]
感谢大佬回复，我的也解决了。我把4g的显卡拔了，只用24g的那一张就解决了

**Comment by GreatStep** [comment]
默认从 0卡开始的
